baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "Noah Kernis - The Blog"
    subtitle = "You can read my blog here. You can leave by turning off your device."
    keywords = "blog itp technology art learning "
    copyright = "All The Rights - All Of Time - All To Noah Kernis"
    menuMore = "Show more"
    readMore = "Read post"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Noah Kernis - The Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"

[privacy]
  [privacy.disqus]
    disable = false

  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

  [privacy.instagram]
    disable = false
    simple = true
    disableInlineCSS = true

  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.vimeo]
    disable = false
    simple = true

  [privacy.youtube]
    disable = false
    privacyEnhanced = true